version: "3.8"

services:
  # runs db
  postgres:
    image: postgres:alpine
    container_name: et-db
    network_mode: host
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  # computes hourly amounts of data
  hourly-stats:
    image: qobiljon/et-agg-values-svc:${AGG_VALUES_IMG_VER}
    container_name: et-agg-values
    network_mode: host
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  # computes aggregate values every three hours
  aggregate-values:
    image: qobiljon/et-hourly-amounts-svc:${HOURLY_STATS_IMG_VER}
    container_name: et-hourly-amounts
    network_mode: host
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  # serves dashboard static data
  nginx-static:
    image: nginx:alpine
    container_name: et-static
    ports:
      - "${STATIC_PORT}:80"
    volumes:
      - ./static-conf/static:/srv
      - ./static-conf/nginx.conf:/etc/nginx/conf.d/default.conf

  # dashboard web app (django)
  dashboard:
    image: qobiljon/dashboard:${DASHBOARD_IMG_VER}
    container_name: et-dashboard
    network_mode: host
    environment:
      STATIC_HOST: host.docker.internal
      STATIC_PORT: ${STATIC_PORT}
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"

  # synchronizes geoplan and easytrack databases (like ETL)
  geoplan-sync:
    image: qobiljon/et_geoplan_db_sync:${GEOPLAN_SYNC_IMG_VER}
    container_name: et-geoplan-sync
    network_mode: host
    env_file:
      - .env
