version: "3.8"

services:
  # runs db
  postgres:
    image: postgres:alpine
    container_name: et-db
    network_mode: host
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  # serves dashboard static data
  nginx-static:
    image: nginx:alpine
    container_name: et-static
    ports:
      - "${STATIC_PORT}:80"
    volumes:
      - ./static-conf/static:/srv
      - ./static-conf/nginx.conf:/etc/nginx/conf.d/default.conf

  # dashboard web app (django)
  dashboard:
    image: qobiljon/dashboard:${DASHBOARD_IMG_VER}
    container_name: et-dashboard
    network_mode: host
    environment:
      STATIC_HOST: host.docker.internal
      STATIC_PORT: ${STATIC_PORT}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"