version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: et-db
    network_mode: host
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  hourly-stats:
    image: qobiljon/et-agg-values-svc:${AGG_VALUES_IMG_VER}
    container_name: et-hourly-amounts
    network_mode: host
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  aggregate-values:
    image: qobiljon/et-hourly-amounts-svc:${HOURLY_STATS_IMG_VER}
    container_name: et-agg-values
    network_mode: host
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
