version: "3.8"

services:
  et-dummy-data:
    image: qobiljon/dummy-data:${DUMMY_DATA_IMG_VER}
    container_name: et-dummy-data
    network_mode: host
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CAMPAIGN_ID: 1
      PARTICIPANT_ID: 1
      DATA_SOURCE_ID: 2
      DATA_TYPE: "Quantitative"
      DATA_RATE: "1Hz"
      FROM_TS: "2022-09-13 10:00:00 +0900"
      TILL_TS: "2022-09-13 16:00:00 +0900"
